# Generated by Django 3.0.3 on 2020-03-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TvShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('status', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('rated', models.CharField(max_length=200)),
                ('score', models.FloatField()),
                ('network', models.CharField(max_length=200)),
                ('released_date', models.CharField(max_length=200)),
                ('show_type', models.CharField(max_length=200)),
                ('run_time', models.TimeField()),
                ('image', models.TextField()),
                ('bg_image', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
